### PR TITLE
Add formatter module

### PR DESCRIPTION
**Pull request by k3ii**

### CODE REVIEW

**Comment by puzzledvacuum** [comment]
Hi @k3ii, have you been able to test the library? If not, how would you go about testing this change?

**Review by ginahorscroft — APPROVED** [review]

**Comment by k3ii** [comment]
@puzzledvacuum , I tested the formatter and it works great 🥳 .
Can you approve it, please?

**Comment by puzzledvacuum** [comment]
@k3ii Can you add [tests](https://github.com/RingierIMU/ritdu-slacker/blob/a8cb8ca97e0bac1ac2c883741a44890dca0c2843/.github/workflows/publish-to-pypi.yml#L34) that will be run when the [action](https://github.com/RingierIMU/ritdu-slacker/blob/a8cb8ca97e0bac1ac2c883741a44890dca0c2843/.github/workflows/publish-to-pypi.yml#L34) is run?

**Review by puzzledvacuum — APPROVED** [review]
💎

**Comment by puzzledvacuum** [comment]
Nice one @k3ii 💪

Once this is merged I can do a deploy then it is live.

**Comment by puzzledvacuum** [comment]
FYI: A deploy is triggered by pushing a [tag](https://github.com/RingierIMU/ritdu-slacker/blob/a8cb8ca97e0bac1ac2c883741a44890dca0c2843/.github/workflows/publish-to-pypi.yml#L10)

**Pull request merged**
