### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by datashaman**
* Use pbr for packaging, does a lot of what you were doing with much less code.
* Get rid of all references to venv and virtualenv in Makefile. Be in a virtualenv (or dont) when you use it. The package build process should not care what environment it's in and should not take part in setting it up.
* Change workflow to do dist (and only publish if it's a tag). This allows us to test dist works correctly without publishing.
* Add tests.

### CODE REVIEW

**Review by pieterza — CHANGES_REQUESTED** [review]
This seems to remove the --version support, unless the packing/magic provides that now?

**Comment by datashaman** [comment]
Added version support back, it reads the package info to get the actual version.

```
$> ritdu-slacker --version
ritdu-slacker, version 1.1.1.dev2
```

**Review by puzzledvacuum — APPROVED** [review]
💎

**Review by matthewnessworthy — APPROVED** [review]
I don't know python, so my approval is of you, not the work ❤️

**Review by pieterza — APPROVED** [review]
Great :)

**Review by pieterza — APPROVED** [review]
Amazing stuff! <3

**Pull request merged**
