### PR TITLE
Allow overriding command to message_template.

### PR DESCRIPTION
**Pull request by pieterza**
We could then start posting rawjson if we wanted as per:

```
curl -H "Accept: application/json" -X POST 'https://fw-slacker.test/api/message-template' --data '{"command": "SlackJson","channel": "UV60NRPDX","project": "ritdu-horizon","message": {"blocks":[{"type":"section","text":```

### CODE REVIEW

**Review by ginahorscroft — APPROVED** [review]

**Review by datashaman — APPROVED** [review]

**Review by dbndave — APPROVED** [review]

**Review by matthewnessworthy — APPROVED** [review]

**Comment by puzzledvacuum** [comment]
@pieterza I was thinking about this last week and was wondering how we would include the new functionality. I have not tested this through `ritdu-slacker` yet but it seems like the message should be json if the command is `SlackJson`? It might just work as we do not change the message that is being passed on.

If so would it not be better to rather extend the code instead of modifying it? I was thinking about a message class that does all the checks depending on the command.

**Review by puzzledvacuum — APPROVED** [review]

**Comment by pieterza** [comment]
> @pieterza I was thinking about this last week and was wondering how we would include the new functionality. I have not tested this through `ritdu-slacker` yet but it seems like the message should be json if the command is `SlackJson`? It might just work as we do not change the message that is being passed on.
> 
> If so would it not be better to rather extend the code instead of modifying it? I was thinking about a message class that does all the checks depending on the command.

Hey @puzzledvacuum ,

I hear that, though the inverse situation is also true.

The code function is called `post_message`, which actually is hardcoded `SimpleMessage` command.
So, it made sense to allow the command to be specified along with the `post_message` function, defaulting to `SimpleMessage` if unset.

I'd like to try avoid having to rename `post_message` to `simple_message` and then creating new copy paste functions for each upstream type, if we can.

**Comment by matthewnessworthy** [comment]
@pieterza each upstream command will have different parameters and different validation, this was intentional as it was made to handle different use-cases without requiring the user to provide a fragile json structure and instead provide specific (mostly scalar) parameters

**Comment by pieterza** [comment]
> @pieterza each upstream command will have different parameters and different validation, this was intentional as it was made to handle different use-cases without requiring the user to provide a fragile json structure and instead provide specific (mostly scalar) parameters

I'll then rather make the post_message more flexible in keeping simplemessage as default, but allowing SlackJson if we add more keywords.  I don't plan/think on using the other methods in this client, as else we'd just be duplicating whatever there is upstream.

Basic messaging and json blob support should be sufficient for any caller program.  Can build fancy blocks in the caller repos, and pass it on.  I'll maybe refactor to do the above prior to merging.  Or compromise and add a new function for pure json and then leave it at that... 😅

**Pull request merged**
